### ISSUE TITLE
Run failure(KeyError: 'C1=CSC(C2=NNN=N2)=C1')

### ISSUE THREAD

**Issue by yuzhou2333** [zaixizhang/MGSSL#11]
hi, when i run this pyhon file:!python pretrain_motif.py
i find some SMILES are not in the clique.txt,how can i fix it and make it run successful?

![image](https://github.com/zaixizhang/MGSSL/assets/74141246/2987f374-acb0-4c66-96df-d7845db21be2)
![image](https://github.com/zaixizhang/MGSSL/assets/74141246/20f972b9-e587-4173-967a-b440db72e46d)

**Comment by yuzhou2333** [comment]
the solution is above the closed issue

**Comment by pearl-rabbit** [comment]
Hello, how did you solve this problem?

**Comment by yuzhou2333** [comment]
> Hello, how did you solve this problem?

Thanks for your letter, it should be caused by the inconsistency of rdkit version, when installing 2020.9.1 May be helpful

**Comment by coderabbittank** [comment]
Hi, I can find the oldest version of rdkit 2020.09.5, can you provide the download address for 2020.9.1?

**Comment by yuzhou2333** [comment]
u can just try the 2020.9.1, if there's a question,i'll refind the version,because it's too long time for me~~

**Comment by yuzhou2333** [comment]
> Hi, I can find the oldest version of rdkit 2020.09.5, can you provide the download address for 2020.9.1?

u can just try the 2020.9.5, if there's a question,i'll refind the version,because it's too long time for me~~
