### ISSUE TITLE
Are there some mistakes in tree decomposition modules?

### ISSUE THREAD

**Issue by 1004766790** [zaixizhang/MGSSL#7]
Dear author, I run the mol_tree.py to preprocess the dataset and generate clique.txt, but it throws the KekulizeException for molecules such as Cc1c(/C=C/c2cc(Br)ccn2)c(O)n2c(nc3ccccc32)c1C#N. I use the decomposition modules on other datsets, it make the same exceptions, can you update the code or give some advice?

**Comment by zaixizhang** [comment]
Hi, thanks for your feedback! Depending on the rdkit version and the smiles format, there may be warnings such as KekulizeException in the motif extraction process. However, they do not influence the proper working of code based on my experience.

**Comment by tengsaisai** [comment]
But it's not a warning. The program won't work.
