### ISSUE TITLE
About Motif-Decomposition

### ISSUE THREAD

**Issue by JongKook-Heo** [zaixizhang/MGSSL#9]
Hi zaixizhang, Thanks for sharing your nice works!

I have some questions about generating cliques and bonds in your code.

1. Is there any reason to set MST_MAX_WEIGHT to 100?(motif_based_pretrain > util > chemutils.py)
1-1. If not, how does the MST_MAX_WEIGHT effect to generated cliques?(i.e. If MST_MAX_WEIGHT raises, it causes almost infinite number of motifs?)

2. In MolTree, When the number of edges connecting BRICS cliques is less then 1, Tree decomp overwrites cliques and edges. Does it okay to change the threshold 1 to any small integer like 2 or 3?

Sincerely,
JongKook Heo

**Comment by zaixizhang** [comment]
Hi JongKook,

Thanks for your interest in our work and the great questions!
1.  The set of MST_MAX_WEIGHT has little influence on the generated cliques. As shown in chemutils.py, we assign smaller weights to edges between cliques/motifs with more atom intersections (MST_MAX_WEIGHT - number of shared atoms). Then we use the minimum_spanning_tree function to select the edges between cliques.
2. Yes, you can change the threshold to other small integers. Generally, tree decomp provides finer molecule decompositions.
